In [ ]:
import tensorflow as tf
import numpy as np

## Create a vector, scalar, matrix and tensor

In [ ]:
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
vector= tf.constant([4,3,12,5])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  3, 12,  5], dtype=int32)>

In [ ]:
matrix = tf.constant([[4,5,9,7],[4,2,7,8]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 5, 9, 7],
       [4, 2, 7, 8]], dtype=int32)>

In [ ]:
tf.random.Generator.from_seed(42)
tensor = tf.random.uniform(shape=[3,4,5,6])
tensor

<tf.Tensor: shape=(3, 4, 5, 6), dtype=float32, numpy=
array([[[[0.72465265, 0.8739778 , 0.7333673 , 0.8349632 , 0.04280269,
          0.14657211],
         [0.91393566, 0.11745656, 0.52581024, 0.10750544, 0.93975437,
          0.34477782],
         [0.6390884 , 0.0014174 , 0.20556867, 0.9169885 , 0.39517522,
          0.02070558],
         [0.7853708 , 0.0777173 , 0.41127443, 0.06333029, 0.9485812 ,
          0.9735178 ],
         [0.05894196, 0.8511206 , 0.11014545, 0.67999077, 0.61563885,
          0.92094886]],

        [[0.10939085, 0.40946507, 0.2672497 , 0.8989773 , 0.17546701,
          0.6913407 ],
         [0.66065717, 0.8070688 , 0.5523157 , 0.2315085 , 0.8887017 ,
          0.66920435],
         [0.8167734 , 0.94939446, 0.40805423, 0.46164668, 0.9995091 ,
          0.91847754],
         [0.5902854 , 0.8175731 , 0.7257463 , 0.5110024 , 0.06099975,
          0.03518224],
         [0.3214029 , 0.00157082, 0.9920217 , 0.5629802 , 0.1401496 ,
          0.96997464]],

        [[0.

## Find the shape, rank and size of the tensors 

In [ ]:
scalar.shape,scalar.ndim,tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
vector.shape,vector.ndim,tf.size(vector)

(TensorShape([4]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
matrix.shape,matrix.ndim,tf.size(matrix)

(TensorShape([2, 4]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [ ]:
tensor.shape,tensor.ndim,tf.size(tensor)

(TensorShape([3, 4, 5, 6]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=360>)

## Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
tf.random.Generator.from_seed(42)
A = tf.random.uniform(seed=42,minval=0,maxval=1,shape=[5,300])
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.40370584, 0.00238454, 0.21895528, ..., 0.82889795, 0.2795303 ,
        0.8489932 ],
       [0.8986019 , 0.35739386, 0.24011791, ..., 0.5068251 , 0.7736579 ,
        0.8722241 ],
       [0.8301755 , 0.6732956 , 0.8681612 , ..., 0.81290936, 0.07930756,
        0.00449634],
       [0.9220072 , 0.8086808 , 0.11941469, ..., 0.09226739, 0.5691445 ,
        0.70605636],
       [0.13224578, 0.4737314 , 0.6060257 , ..., 0.63301027, 0.00664556,
        0.40782893]], dtype=float32)>

In [ ]:
tf.random.Generator.from_seed(42)
B = tf.random.uniform(seed=42,minval=0,maxval=1,shape=[5,300])
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.30655718, 0.65554893, 0.49194705, ..., 0.34030926, 0.38490272,
        0.01581812],
       [0.92101336, 0.86649466, 0.1880058 , ..., 0.08662891, 0.9649701 ,
        0.37370658],
       [0.74968433, 0.3097185 , 0.21021307, ..., 0.5211786 , 0.8617159 ,
        0.93096995],
       [0.92950284, 0.41946328, 0.7879014 , ..., 0.48741996, 0.17104745,
        0.7414119 ],
       [0.17429519, 0.10320091, 0.11817622, ..., 0.99018204, 0.9475752 ,
        0.16960335]], dtype=float32)>

## Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
A * B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.12375892, 0.00156318, 0.10771441, ..., 0.28208166, 0.10759196,
        0.01342948],
       [0.8276243 , 0.30967987, 0.04514356, ..., 0.04390571, 0.74655676,
        0.32595587],
       [0.6223696 , 0.2085321 , 0.18249883, ..., 0.42367098, 0.06834058,
        0.00418595],
       [0.85700834, 0.33921188, 0.094087  , ..., 0.04497297, 0.09735071,
        0.5234786 ],
       [0.0230498 , 0.04888951, 0.07161783, ..., 0.6267954 , 0.00629717,
        0.06916915]], dtype=float32)>

## Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.reshape(A,shape=[300,5]) @ B

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.75548047, 0.55820394, 0.62310505, ..., 0.99593043, 0.941494  ,
        0.5993406 ],
       [1.288512  , 1.4434901 , 0.8252201 , ..., 0.63552004, 1.3138407 ,
        0.52449965],
       [1.458969  , 0.9987241 , 1.1770642 , ..., 1.4691434 , 1.3298794 ,
        1.0679559 ],
       ...,
       [1.7154882 , 1.2631197 , 1.1044413 , ..., 1.2150955 , 1.5613527 ,
        1.3525355 ],
       [1.7399302 , 1.0136713 , 1.1340758 , ..., 1.3737065 , 1.476086  ,
        1.5970099 ],
       [1.4797409 , 1.3796309 , 0.6866577 , ..., 1.0496744 , 1.9513816 ,
        0.96134657]], dtype=float32)>

In [ ]:
X = tf.random.uniform(minval=0,maxval=1,shape=[224, 224, 3])
X

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.20867515, 0.99178505, 0.93855035],
        [0.39060402, 0.9630536 , 0.79308605],
        [0.7961867 , 0.32339478, 0.6982813 ],
        ...,
        [0.24073231, 0.69161355, 0.41599977],
        [0.98417425, 0.3405342 , 0.10520291],
        [0.638885  , 0.85880506, 0.43319523]],

       [[0.12049651, 0.04309213, 0.68513465],
        [0.42894256, 0.66008174, 0.2776854 ],
        [0.8735981 , 0.70495975, 0.17586446],
        ...,
        [0.587471  , 0.37336934, 0.9526644 ],
        [0.783569  , 0.88827336, 0.6628952 ],
        [0.76870096, 0.25163174, 0.13088524]],

       [[0.27846217, 0.5945153 , 0.38370705],
        [0.14633584, 0.48290026, 0.4459213 ],
        [0.43053055, 0.10878778, 0.16041255],
        ...,
        [0.93305683, 0.59580445, 0.58861244],
        [0.3924799 , 0.4369725 , 0.43680584],
        [0.19065583, 0.7600212 , 0.895789  ]],

       ...,

       [[0.8219352 , 0.44418824, 0.33218527],
        [0.97

## Find the min and max values of the tensor

In [ ]:
tf.reduce_min(X[0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.00045073032>

In [ ]:
tf.reduce_max(X[0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.9988575>

## Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
H = tf.constant(X,shape=[1,224,224,3])
H.shape

TensorShape([1, 224, 224, 3])

In [ ]:
H_squeezed = tf.squeeze(H)
H_squeezed.shape

TensorShape([224, 224, 3])

## Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
G = tf.constant(np.random.randint(1,10,size=(10)))
G

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([7, 3, 5, 3, 5, 5, 3, 2, 3, 4])>

In [ ]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

## One-hot encode the tensor G

In [ ]:
tf.one_hot(G,depth=(10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>